version: "3"
services: 
  nexus:
    image: "sonatype/nexus3:3.15.2"
    container_name: "nexus"
    restart: "always"
    ports: 
      - "8081:8081"
    # 为了可以使用nfs存储
    volumes: 
      - "./nexus-data:/nexus-data"

#volumes: 
#  nexus-data:
