version: "3"
services: 
  nginx:
    image: "nginx:1.14.2"
    container_name: "nginx"
    restart: "always"
    volumes: 
      - "nginx-etc:/etc/nginx/"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-log:/var/log/nginx/"
    ports: 
      - "80:80"
    networks: 
      - "nginx"
volumes: 
  nginx-etc:
  nginx-html:
  nginx-log:
networks: 
  nginx: