version: "3"
services:
  jenkins:
    image: "jenkins/jenkins:lts-alpine"
    container_name: "jenkins"
    restart: "always"
    ports: 
      - "8080:8080"
    volumes:
      - "./jenkins/jenkins_home:/var/jenkins_home:rw"